/* Generated By:JavaCC: Do not edit this line. OO1ParserConstants.java */
package plp.orientadaObjetos1.parser;

public interface OO1ParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int AND = 9;
  int OR = 10;
  int NOT = 11;
  int LENGTH = 12;
  int TRUE = 13;
  int FALSE = 14;
  int VAR = 15;
  int COMAND_SKIP = 16;
  int WHILE = 17;
  int DO = 18;
  int READ = 19;
  int WRITE = 20;
  int IF = 21;
  int THEN = 22;
  int ELSE = 23;
  int NEW = 24;
  int THIS = 25;
  int CLASSE = 26;
  int NULL = 27;
  int PROC = 28;
  int INT = 29;
  int BOOLEAN = 30;
  int STRING = 31;
  int INTEGER_LITERAL = 32;
  int DECIMAL_LITERAL = 33;
  int HEX_LITERAL = 34;
  int OCTAL_LITERAL = 35;
  int STRING_LITERAL = 36;
  int IDENTIFIER = 37;
  int LETTER = 38;
  int DIGIT = 39;
  int LPAREN = 40;
  int RPAREN = 41;
  int LBRACE = 42;
  int RBRACE = 43;
  int LBRACKET = 44;
  int RBRACKET = 45;
  int SEMICOLON = 46;
  int COMMA = 47;
  int DOT = 48;
  int ATTRIB = 49;
  int ASSIGN = 50;
  int GT = 51;
  int LT = 52;
  int BANG = 53;
  int TILDE = 54;
  int HOOK = 55;
  int COLON = 56;
  int EQ = 57;
  int LE = 58;
  int GE = 59;
  int NE = 60;
  int SC_OR = 61;
  int SC_AND = 62;
  int CONCAT = 63;
  int PLUS = 64;
  int MINUS = 65;
  int STAR = 66;
  int SLASH = 67;
  int BIT_AND = 68;
  int BIT_OR = 69;
  int XOR = 70;
  int REM = 71;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"var\"",
    "\"skip\"",
    "\"while\"",
    "\"do\"",
    "\"read\"",
    "\"write\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"new\"",
    "\"this\"",
    "\"classe\"",
    "\"null\"",
    "\"proc\"",
    "\"int\"",
    "\"boolean\"",
    "\"string\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":=\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
  };

}
