/* Generated By:JavaCC: Do not edit this line. Exp2ParserConstants.java */
package plp.expressions2.parser;

public interface Exp2ParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int AND = 9;
  int OR = 10;
  int NOT = 11;
  int LENGTH = 12;
  int TRUE = 13;
  int FALSE = 14;
  int LET = 15;
  int VAR = 16;
  int IN = 17;
  int INTEGER_LITERAL = 18;
  int DECIMAL_LITERAL = 19;
  int HEX_LITERAL = 20;
  int OCTAL_LITERAL = 21;
  int STRING_LITERAL = 22;
  int IDENTIFIER = 23;
  int LETTER = 24;
  int DIGIT = 25;
  int LPAREN = 26;
  int RPAREN = 27;
  int LBRACE = 28;
  int RBRACE = 29;
  int LBRACKET = 30;
  int RBRACKET = 31;
  int SEMICOLON = 32;
  int COMMA = 33;
  int DOT = 34;
  int ASSIGN = 35;
  int GT = 36;
  int LT = 37;
  int BANG = 38;
  int TILDE = 39;
  int HOOK = 40;
  int COLON = 41;
  int EQ = 42;
  int LE = 43;
  int GE = 44;
  int NE = 45;
  int SC_OR = 46;
  int SC_AND = 47;
  int CONCAT = 48;
  int PLUS = 49;
  int MINUS = 50;
  int STAR = 51;
  int SLASH = 52;
  int BIT_AND = 53;
  int BIT_OR = 54;
  int XOR = 55;
  int REM = 56;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"let\"",
    "\"var\"",
    "\"in\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
  };

}
