/* Generated By:JavaCC: Do not edit this line. Func1ParserConstants.java */
package plp.functional1.parser;

public interface Func1ParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int AND = 9;
  int OR = 10;
  int NOT = 11;
  int LENGTH = 12;
  int TRUE = 13;
  int FALSE = 14;
  int LET = 15;
  int VAR = 16;
  int IN = 17;
  int IF = 18;
  int THEN = 19;
  int ELSE = 20;
  int FUNC = 21;
  int INTEGER_LITERAL = 22;
  int DECIMAL_LITERAL = 23;
  int HEX_LITERAL = 24;
  int OCTAL_LITERAL = 25;
  int STRING_LITERAL = 26;
  int IDENTIFIER = 27;
  int LETTER = 28;
  int DIGIT = 29;
  int LPAREN = 30;
  int RPAREN = 31;
  int LBRACE = 32;
  int RBRACE = 33;
  int LBRACKET = 34;
  int RBRACKET = 35;
  int SEMICOLON = 36;
  int COMMA = 37;
  int DOT = 38;
  int ASSIGN = 39;
  int GT = 40;
  int LT = 41;
  int BANG = 42;
  int TILDE = 43;
  int HOOK = 44;
  int COLON = 45;
  int EQ = 46;
  int LE = 47;
  int GE = 48;
  int NE = 49;
  int SC_OR = 50;
  int SC_AND = 51;
  int CONCAT = 52;
  int PLUS = 53;
  int MINUS = 54;
  int STAR = 55;
  int SLASH = 56;
  int BIT_AND = 57;
  int BIT_OR = 58;
  int XOR = 59;
  int REM = 60;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "\"let\"",
    "\"var\"",
    "\"in\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"fun\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
  };

}
