/* Generated By:JavaCC: Do not edit this line. Exp1ParserConstants.java */
package plp.expressions1.parser;

public interface Exp1ParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int FORMAL_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int AND = 9;
  int OR = 10;
  int NOT = 11;
  int LENGTH = 12;
  int TRUE = 13;
  int FALSE = 14;
  int INTEGER_LITERAL = 15;
  int DECIMAL_LITERAL = 16;
  int HEX_LITERAL = 17;
  int OCTAL_LITERAL = 18;
  int STRING_LITERAL = 19;
  int IDENTIFIER = 20;
  int LETTER = 21;
  int DIGIT = 22;
  int LPAREN = 23;
  int RPAREN = 24;
  int LBRACE = 25;
  int RBRACE = 26;
  int LBRACKET = 27;
  int RBRACKET = 28;
  int SEMICOLON = 29;
  int COMMA = 30;
  int DOT = 31;
  int ASSIGN = 32;
  int GT = 33;
  int LT = 34;
  int BANG = 35;
  int TILDE = 36;
  int HOOK = 37;
  int COLON = 38;
  int EQ = 39;
  int LE = 40;
  int GE = 41;
  int NE = 42;
  int SC_OR = 43;
  int SC_AND = 44;
  int CONCAT = 45;
  int PLUS = 46;
  int MINUS = 47;
  int STAR = 48;
  int SLASH = 49;
  int BIT_AND = 50;
  int BIT_OR = 51;
  int XOR = 52;
  int REM = 53;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"length\"",
    "\"true\"",
    "\"false\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
  };

}
